version: '3.1'
services:
  kongmongo:
    build: ./database
    image: kong-mongo
    restart: always
    ports:
      - 27017:27017
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
      MONGO_INITDB_DATABASE: KongServices
  app:
    build: ./app
    image: kong-service
    ports:
      - 8000:8000
    depends_on: 
      - kongmongo
    environment:
      MONGODB_URI: 'mongodb://root:test@kongmongo:27017'